version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Root directory where requirements.txt is located
    schedule:
      interval: "weekly" # Check for updates weekly
    ignore:
      - dependency-name: "torch"
      - dependency-name: "transformers"
      - dependency-name: "torchvision"
