name: Assign PR

on:
  pull_request:
    types: [review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  assign_or_unassign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign or unassign reviewers
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const action = context.payload.action;

            if (action === 'review_requested') {
              const pr = context.payload.pull_request;
              const reviewer = context.payload.requested_reviewer;

              if (reviewer) {
                const assignees = [...new Set([
                  ...pr.assignees.map(u => u.login),
                  reviewer.login
                ])];

                await github.rest.issues.update({
                  owner,
                  repo,
                  issue_number: pr.number,
                  assignees
                });
              }
            }

            if (context.eventName === 'pull_request_review' && action === 'submitted') {
              const pr = context.payload.pull_request;
              const reviewer = context.payload.review.user.login;

              const assignees = pr.assignees
                .map(u => u.login)
                .filter(login => login !== reviewer);

              await github.rest.issues.update({
                owner,
                repo,
                issue_number: pr.number,
                assignees
              });
            }
