name: Check PR Size Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: BedrockStreaming/pr-size-labeler@v2.0.0
        with:
          toke: ${{ secrets.GITHUB_TOKEN }}
