name: Check PR Size Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: BedrockStreaming/pr-size-labeler@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/xs"
          s_label: "size/s"
          m_label: "size/m"
          l_label: "size/l"
          xl_label: "size/xl"
