name: Create Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DockerHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate automatic changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 🐳 Docker Image
            Docker Hub URL: [View Package](https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUB_USERNAME }}/app-ras-25/tags)

            ```
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-ras-25:${{ github.ref_name }}
            ```

            ## 📋 Changelog

            ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
