name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add size label
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions || 0;
            const deletions = pr.deletions || 0;
            const totalChanges = additions + deletions;

            // Define size thresholds
            let sizeLabel;
            if (totalChanges < 50) {
              sizeLabel = 'size:small';
            } else if (totalChanges < 200) {
              sizeLabel = 'size:medium';
            } else {
              sizeLabel = 'size:large';
            }

            // Remove existing size labels
            const existingLabels = pr.labels || [];
            const sizeLabels = existingLabels.filter(label => label.name.startsWith('size/'));

            for (const label of sizeLabels) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                name: label.name
              });
            }

            // Add new size label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: [sizeLabel]
            });

            core.info(`Added ${sizeLabel} label (${totalChanges} total changes: +${additions} -${deletions})`);
